# Generated by Django 3.2.12 on 2022-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_url', models.TextField()),
                ('impo', models.BooleanField()),
                ('site_con', models.TextField()),
            ],
        ),
    ]
